### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by G-White-BOD** [PIC-Nico/Ease#1]
Hi Nico, habe gesehen, dass Deine Webseite nicht mehr funktioniert. Evtl. ist Dir das gar nicht aufgefallen...Hab gesucht Dir eine Email zu schreiben, konnte aber nur den Link zu Deinem Accout hier finden. Vielleicht magst Du die Seite mal prüfen. Fand Deine Inhalte immer super spannend zu sehen. Viele grüße, Georg

Den Issue würde ich dann natürlich wieder löschen :-)

**Comment by PIC-Nico** [comment]
Hi, leider ist meine Webseite schon seit einer Weile nicht mehr online. Habe mich dazu entschlossen, sie nicht weiter zu pflegen bzw. fehlt mir einfach die Zeit.

**Comment by G-White-BOD** [comment]
Hallo Nico,Das ist sehr schade, kann ich aber verstehen. Wäre es denkbar einen Abzug von dem Mini-Anzeigemodul zu erhalten? PDF und evtl den Quell Code vom PIC?Hab weiter Spaß an Deiner Arbeit! Hat mich immer super inspiriert :-)Alles Gute und vielleicht bekomme ja eine positive Antwort von Dir.Besten Dank,Gruß Georg Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Nicolas Pannwitz ***@***.***> Datum: 12.06.21  20:32  (GMT+01:00) An: PIC-Nico/Ease ***@***.***> Cc: G-White-BOD ***@***.***>, Author ***@***.***> Betreff: Re: [PIC-Nico/Ease] Kontakt (#1) 
Hi, leider ist meine Webseite schon seit einer Weile nicht mehr online. Habe mich dazu entschlossen, sie nicht weiter zu pflegen bzw. fehlt mir einfach die Zeit.
